"""Initial migration

Revision ID: 9f623013eb56
Revises:
Create Date: 2024-06-12 20:26:10.310059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f623013eb56"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("local_id", sa.Integer(), nullable=True),
        sa.Column("cards_init", sa.String(), nullable=True),
        sa.Column("cards_current", sa.String(), nullable=True),
        sa.Column("cards_played", sa.String(), nullable=True),
        sa.Column("bolt_count", sa.Integer(), nullable=True),
        sa.Column("barrel_count", sa.Integer(), nullable=True),
        sa.Column("on_barrel_since", sa.Integer(), nullable=True),
        sa.Column("round_point", sa.Integer(), nullable=True),
        sa.Column("point", sa.Integer(), nullable=True),
        sa.Column("max_biddable_amount", sa.Integer(), nullable=True),
        sa.Column("silent", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("player0_id", sa.String(), nullable=True),
        sa.Column("player1_id", sa.String(), nullable=True),
        sa.Column("player2_id", sa.String(), nullable=True),
        sa.Column("creation_date", sa.String(), nullable=True),
        sa.Column("game_state", sa.String(), nullable=True),
        sa.Column("current_round", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player0_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=True),
        sa.Column("on_barrel", sa.Integer(), nullable=True),
        sa.Column("activated_pair", sa.String(), nullable=True),
        sa.Column("talon", sa.String(), nullable=True),
        sa.Column("bid_starter", sa.Integer(), nullable=True),
        sa.Column("bids", sa.String(), nullable=True),
        sa.Column("bid_winner", sa.Integer(), nullable=True),
        sa.Column("final_bid_amount", sa.Integer(), nullable=True),
        sa.Column("trick", sa.String(), nullable=True),
        sa.Column("trick_turn", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("round")
    op.drop_table("game")
    op.drop_table("player")
    # ### end Alembic commands ###
